PRAGMA foreign_keys = ON;

-- ============================================================
-- BASE TABLE: metadata
-- ============================================================

CREATE TABLE IF NOT EXISTS metadata (
    accession TEXT PRIMARY KEY,

    organism_name TEXT,
    genbank_refseq TEXT,
    assembly TEXT,

    release_date TEXT,

    isolate TEXT,
    species TEXT,

    length INTEGER CHECK (length IS NULL OR length >= 0),

    nuc_completeness TEXT,
    genotype TEXT,
    segment TEXT,
    ha_subtype TEXT,
    na_subtype TEXT,

    country TEXT,
    host TEXT,

    collection_date TEXT,

    comment TEXT
);

-- ============================================================
-- BASE TABLE: sequences
-- ============================================================

CREATE TABLE IF NOT EXISTS sequences (
    sequence_id INTEGER PRIMARY KEY AUTOINCREMENT,

    accession TEXT NOT NULL UNIQUE,
    description TEXT,
    sequence TEXT NOT NULL CHECK (
        length(sequence) > 0
        AND length(sequence) <= 30000
    ),

    -- Precomputed ambiguous base counts (populated by the ETL).
    n_N INTEGER NOT NULL DEFAULT 0 CHECK (n_N >= 0),
    n_degenerate INTEGER NOT NULL DEFAULT 0 CHECK (n_degenerate >= 0),

    -- JSON object with per-degenerate-base counts: {"R": 0, "Y": 1, ...}
    degenerate_breakdown TEXT,

    FOREIGN KEY (accession)
        REFERENCES metadata(accession)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- BASE TABLE: clusters
-- ============================================================

CREATE TABLE IF NOT EXISTS clusters (
    organism TEXT NOT NULL,
    cluster_number TEXT NOT NULL,

    centroid TEXT NOT NULL,

    PRIMARY KEY (organism, cluster_number),

    FOREIGN KEY (centroid)
        REFERENCES metadata(accession)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ============================================================
-- BASE TABLE: cluster_composition
-- ============================================================

CREATE TABLE IF NOT EXISTS cluster_composition (
    organism TEXT NOT NULL,
    cluster_number TEXT NOT NULL,

    accession TEXT NOT NULL UNIQUE,

    identity_to_centroid REAL CHECK (
        identity_to_centroid IS NULL
        OR (
            identity_to_centroid >= 0.0
            AND identity_to_centroid <= 100.0
        )
    ),

    PRIMARY KEY (accession, organism, cluster_number),

    FOREIGN KEY (accession)
        REFERENCES metadata(accession)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    FOREIGN KEY (organism, cluster_number)
        REFERENCES clusters(organism, cluster_number)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- ============================================================
-- DERIVED TABLE: cluster_summary
-- ============================================================
--
-- One row per complete cluster.
-- Generated by the ETL after metadata, sequences, clusters and
-- cluster_composition have been loaded.
-- ============================================================

CREATE TABLE IF NOT EXISTS cluster_summary (
    organism TEXT NOT NULL,
    cluster_number TEXT NOT NULL,

    centroid TEXT NOT NULL,

    segment TEXT,
    n_segments INTEGER NOT NULL DEFAULT 0 CHECK (n_segments >= 0),

    n_sequences INTEGER NOT NULL DEFAULT 0 CHECK (n_sequences >= 0),
    n_hosts INTEGER NOT NULL DEFAULT 0 CHECK (n_hosts >= 0),
    n_countries INTEGER NOT NULL DEFAULT 0 CHECK (n_countries >= 0),
    n_genotypes INTEGER NOT NULL DEFAULT 0 CHECK (n_genotypes >= 0),

    length_min REAL CHECK (length_min IS NULL OR length_min >= 0),
    length_q1 REAL CHECK (length_q1 IS NULL OR length_q1 >= 0),
    length_mean REAL CHECK (length_mean IS NULL OR length_mean >= 0),
    length_median REAL CHECK (length_median IS NULL OR length_median >= 0),
    length_q3 REAL CHECK (length_q3 IS NULL OR length_q3 >= 0),
    length_max REAL CHECK (length_max IS NULL OR length_max >= 0),
    length_std REAL CHECK (length_std IS NULL OR length_std >= 0),

    PRIMARY KEY (organism, cluster_number),

    FOREIGN KEY (organism, cluster_number)
        REFERENCES clusters(organism, cluster_number)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    FOREIGN KEY (centroid)
        REFERENCES metadata(accession)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ============================================================
-- DERIVED TABLE: cluster_background_counts
-- ============================================================
--
-- Long/tidy background-count table.
--
-- One row per:
--   organism
--   cluster_number
--   segment
--   background_type
--   background_value
--
-- background_type is currently:
--   host
--   country
--   genotype
-- ============================================================

CREATE TABLE IF NOT EXISTS cluster_background_counts (
    organism TEXT NOT NULL,
    cluster_number TEXT NOT NULL,

    centroid TEXT NOT NULL,

    segment TEXT,

    background_type TEXT NOT NULL CHECK (
        background_type IN ('host', 'country', 'genotype')
    ),

    background_value TEXT NOT NULL,

    n_sequences INTEGER NOT NULL DEFAULT 0 CHECK (n_sequences >= 0),

    PRIMARY KEY (
        organism,
        cluster_number,
        segment,
        background_type,
        background_value
    ),

    FOREIGN KEY (organism, cluster_number)
        REFERENCES clusters(organism, cluster_number)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    FOREIGN KEY (centroid)
        REFERENCES metadata(accession)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ============================================================
-- DERIVED TABLE: cluster_descriptors
-- ============================================================
--
-- One row per complete cluster.
--
-- *_json columns store JSON-encoded dictionaries, for example:
--   {"H5N1": 42, "H5N8": 3}
-- ============================================================

CREATE TABLE IF NOT EXISTS cluster_descriptors (
    organism TEXT NOT NULL,
    cluster_number TEXT NOT NULL,

    representative TEXT NOT NULL,

    n_sequences INTEGER NOT NULL DEFAULT 0 CHECK (n_sequences >= 0),

    genotypes_json TEXT,
    segments_json TEXT,
    hosts_json TEXT,
    countries_json TEXT,

    dominant_genotype TEXT,
    dominant_segment TEXT,
    dominant_host TEXT,
    dominant_country TEXT,

    n_genotypes INTEGER NOT NULL DEFAULT 0 CHECK (n_genotypes >= 0),
    n_segments INTEGER NOT NULL DEFAULT 0 CHECK (n_segments >= 0),
    n_hosts INTEGER NOT NULL DEFAULT 0 CHECK (n_hosts >= 0),
    n_countries INTEGER NOT NULL DEFAULT 0 CHECK (n_countries >= 0),

    is_singleton INTEGER NOT NULL DEFAULT 0 CHECK (is_singleton IN (0, 1)),
    is_mixed_genotype INTEGER NOT NULL DEFAULT 0 CHECK (is_mixed_genotype IN (0, 1)),
    is_mixed_segment INTEGER NOT NULL DEFAULT 0 CHECK (is_mixed_segment IN (0, 1)),
    is_multi_host INTEGER NOT NULL DEFAULT 0 CHECK (is_multi_host IN (0, 1)),
    is_multi_country INTEGER NOT NULL DEFAULT 0 CHECK (is_multi_country IN (0, 1)),

    length_min REAL CHECK (length_min IS NULL OR length_min >= 0),
    length_mean REAL CHECK (length_mean IS NULL OR length_mean >= 0),
    length_median REAL CHECK (length_median IS NULL OR length_median >= 0),
    length_max REAL CHECK (length_max IS NULL OR length_max >= 0),
    length_std REAL CHECK (length_std IS NULL OR length_std >= 0),

    PRIMARY KEY (organism, cluster_number),

    FOREIGN KEY (organism, cluster_number)
        REFERENCES clusters(organism, cluster_number)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    FOREIGN KEY (representative)
        REFERENCES metadata(accession)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ============================================================
-- DERIVED TABLE: cluster_filter_counts
-- ============================================================
--
-- Fast lookup table for combined cluster filters.
--
-- One row per observed combination:
--   organism
--   cluster_number
--   segment
--   genotype
--   host
--   country
--
-- Important:
--   In derived tables, the ETL should normalise missing segment/genotype/
--   host/country to a controlled string such as 'Unknown', because NULL
--   values inside composite PRIMARY KEY columns can behave unexpectedly
--   in SQLite.
-- ============================================================

CREATE TABLE IF NOT EXISTS cluster_filter_counts (
    organism TEXT NOT NULL,
    cluster_number TEXT NOT NULL,

    centroid TEXT NOT NULL,

    segment TEXT NOT NULL DEFAULT 'Unknown',
    genotype TEXT NOT NULL DEFAULT 'Unknown',
    ha_subtype TEXT NOT NULL DEFAULT 'Unknown',
    na_subtype TEXT NOT NULL DEFAULT 'Unknown',
    host TEXT NOT NULL DEFAULT 'Unknown',
    country TEXT NOT NULL DEFAULT 'Unknown',

    n_sequences INTEGER NOT NULL DEFAULT 0 CHECK (n_sequences >= 0),

    PRIMARY KEY (
        organism,
        cluster_number,
        segment,
        genotype,
        ha_subtype,
        na_subtype,
        host,
        country
    ),

    FOREIGN KEY (organism, cluster_number)
        REFERENCES clusters(organism, cluster_number)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    FOREIGN KEY (centroid)
        REFERENCES metadata(accession)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ============================================================
-- VIEW: cluster_member_metadata
-- ============================================================
--
-- Convenience view for cluster member browsing and FASTA export.
-- ============================================================

CREATE VIEW IF NOT EXISTS cluster_member_metadata AS
SELECT
    cc.organism,
    cc.cluster_number,
    c.centroid,

    cc.accession,
    cc.identity_to_centroid,

    m.organism_name,
    m.genbank_refseq,
    m.assembly,
    m.release_date,
    m.isolate,
    m.species,
    m.length,
    m.nuc_completeness,
    m.genotype,
    m.ha_subtype,
    m.na_subtype,
    m.segment,
    m.country,
    m.host,
    m.collection_date,
    m.comment,

    s.description,
    s.sequence

FROM cluster_composition cc
LEFT JOIN clusters c
    ON cc.organism = c.organism
    AND cc.cluster_number = c.cluster_number
LEFT JOIN metadata m
    ON cc.accession = m.accession
LEFT JOIN sequences s
    ON cc.accession = s.accession;

-- ============================================================
-- INDEXES: metadata
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_metadata_organism_name
ON metadata(organism_name);

CREATE INDEX IF NOT EXISTS idx_metadata_genbank_refseq
ON metadata(genbank_refseq);

CREATE INDEX IF NOT EXISTS idx_metadata_assembly
ON metadata(assembly);

CREATE INDEX IF NOT EXISTS idx_metadata_release_date
ON metadata(release_date);

CREATE INDEX IF NOT EXISTS idx_metadata_species
ON metadata(species);

CREATE INDEX IF NOT EXISTS idx_metadata_length
ON metadata(length);

CREATE INDEX IF NOT EXISTS idx_metadata_nuc_completeness
ON metadata(nuc_completeness);

CREATE INDEX IF NOT EXISTS idx_metadata_genotype
ON metadata(genotype);

CREATE INDEX IF NOT EXISTS idx_metadata_ha_subtype
ON metadata(ha_subtype);

CREATE INDEX IF NOT EXISTS idx_metadata_na_subtype
ON metadata(na_subtype);

CREATE INDEX IF NOT EXISTS idx_metadata_segment
ON metadata(segment);

CREATE INDEX IF NOT EXISTS idx_metadata_country
ON metadata(country);

CREATE INDEX IF NOT EXISTS idx_metadata_host
ON metadata(host);

CREATE INDEX IF NOT EXISTS idx_metadata_collection_date
ON metadata(collection_date);

-- ============================================================
-- INDEXES: sequences
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_sequences_accession
ON sequences(accession);

CREATE INDEX IF NOT EXISTS idx_sequences_n_N
ON sequences(n_N);

CREATE INDEX IF NOT EXISTS idx_sequences_n_degenerate
ON sequences(n_degenerate);

-- ============================================================
-- INDEXES: clusters
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_clusters_centroid
ON clusters(centroid);

CREATE INDEX IF NOT EXISTS idx_clusters_organism
ON clusters(organism);

CREATE INDEX IF NOT EXISTS idx_clusters_cluster_number
ON clusters(cluster_number);

-- ============================================================
-- INDEXES: cluster_composition
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_cluster_composition_accession
ON cluster_composition(accession);

CREATE INDEX IF NOT EXISTS idx_cluster_composition_cluster
ON cluster_composition(organism, cluster_number);

CREATE INDEX IF NOT EXISTS idx_cluster_composition_identity
ON cluster_composition(identity_to_centroid);

-- ============================================================
-- INDEXES: cluster_summary
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_cluster_summary_centroid
ON cluster_summary(centroid);

CREATE INDEX IF NOT EXISTS idx_cluster_summary_segment
ON cluster_summary(segment);

CREATE INDEX IF NOT EXISTS idx_cluster_summary_size
ON cluster_summary(n_sequences);

CREATE INDEX IF NOT EXISTS idx_cluster_summary_organism_segment
ON cluster_summary(organism, segment);

CREATE INDEX IF NOT EXISTS idx_cluster_summary_segment_size
ON cluster_summary(segment, n_sequences);

CREATE INDEX IF NOT EXISTS idx_cluster_summary_n_segments
ON cluster_summary(n_segments);

-- ============================================================
-- INDEXES: cluster_background_counts
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_cluster_background_cluster
ON cluster_background_counts(organism, cluster_number);

CREATE INDEX IF NOT EXISTS idx_cluster_background_centroid
ON cluster_background_counts(centroid);

CREATE INDEX IF NOT EXISTS idx_cluster_background_segment
ON cluster_background_counts(segment);

CREATE INDEX IF NOT EXISTS idx_cluster_background_type_value
ON cluster_background_counts(background_type, background_value);

CREATE INDEX IF NOT EXISTS idx_cluster_background_segment_type_value
ON cluster_background_counts(segment, background_type, background_value);

CREATE INDEX IF NOT EXISTS idx_cluster_background_count
ON cluster_background_counts(n_sequences);

-- ============================================================
-- INDEXES: cluster_descriptors
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_cluster_descriptors_representative
ON cluster_descriptors(representative);

CREATE INDEX IF NOT EXISTS idx_cluster_descriptors_dominant_segment
ON cluster_descriptors(dominant_segment);

CREATE INDEX IF NOT EXISTS idx_cluster_descriptors_dominant_genotype
ON cluster_descriptors(dominant_genotype);

CREATE INDEX IF NOT EXISTS idx_cluster_descriptors_dominant_host
ON cluster_descriptors(dominant_host);

CREATE INDEX IF NOT EXISTS idx_cluster_descriptors_dominant_country
ON cluster_descriptors(dominant_country);

CREATE INDEX IF NOT EXISTS idx_cluster_descriptors_size
ON cluster_descriptors(n_sequences);

CREATE INDEX IF NOT EXISTS idx_cluster_descriptors_singleton
ON cluster_descriptors(is_singleton);

CREATE INDEX IF NOT EXISTS idx_cluster_descriptors_mixed_genotype
ON cluster_descriptors(is_mixed_genotype);

CREATE INDEX IF NOT EXISTS idx_cluster_descriptors_mixed_segment
ON cluster_descriptors(is_mixed_segment);

CREATE INDEX IF NOT EXISTS idx_cluster_descriptors_multi_host
ON cluster_descriptors(is_multi_host);

CREATE INDEX IF NOT EXISTS idx_cluster_descriptors_multi_country
ON cluster_descriptors(is_multi_country);

-- ============================================================
-- INDEXES: cluster_filter_counts
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_cluster_filter_cluster
ON cluster_filter_counts(organism, cluster_number);

CREATE INDEX IF NOT EXISTS idx_cluster_filter_centroid
ON cluster_filter_counts(centroid);

CREATE INDEX IF NOT EXISTS idx_cluster_filter_segment
ON cluster_filter_counts(segment);

CREATE INDEX IF NOT EXISTS idx_cluster_filter_genotype
ON cluster_filter_counts(genotype);

CREATE INDEX IF NOT EXISTS idx_cluster_filter_ha_subtype
ON cluster_filter_counts(ha_subtype);

CREATE INDEX IF NOT EXISTS idx_cluster_filter_na_subtype
ON cluster_filter_counts(na_subtype);

CREATE INDEX IF NOT EXISTS idx_cluster_filter_host
ON cluster_filter_counts(host);

CREATE INDEX IF NOT EXISTS idx_cluster_filter_country
ON cluster_filter_counts(country);

CREATE INDEX IF NOT EXISTS idx_cluster_filter_segment_host
ON cluster_filter_counts(segment, host);

CREATE INDEX IF NOT EXISTS idx_cluster_filter_segment_genotype
ON cluster_filter_counts(segment, genotype);

CREATE INDEX IF NOT EXISTS idx_cluster_filter_segment_country
ON cluster_filter_counts(segment, country);

CREATE INDEX IF NOT EXISTS idx_cluster_filter_segment_host_country
ON cluster_filter_counts(segment, host, country);

CREATE INDEX IF NOT EXISTS idx_cluster_filter_segment_ha_subtype
ON cluster_filter_counts(segment, ha_subtype);

CREATE INDEX IF NOT EXISTS idx_cluster_filter_segment_na_subtype
ON cluster_filter_counts(segment, na_subtype);

CREATE INDEX IF NOT EXISTS idx_cluster_filter_segment_genotype_host_country
ON cluster_filter_counts(segment, genotype, host, country);

CREATE INDEX IF NOT EXISTS idx_cluster_filter_count
ON cluster_filter_counts(n_sequences);